apiVersion: apps/v1
kind: Deployment
metadata:
  name: clasificador-deployment
spec:
  replicas: 3  # Número de réplicas
  selector:
    matchLabels:
      app: clasificador
  template:
    metadata:
      labels:
        app: clasificador
    spec:
      containers:
      - name: clasificador
        image: acrtestflask.azurecr.io/clasificador:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clasificador-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: clasificador